//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OxyPlot_Drawing_Toolbar {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTips {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTips() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OxyPlot_Drawing_Toolbar.ToolTips", typeof(ToolTips).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all annotations on the chart..
        /// </summary>
        internal static string DeleteAllAnnots {
            get {
                return ResourceManager.GetString("DeleteAllAnnots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete annotations clicked on..
        /// </summary>
        internal static string DeleteAnnot {
            get {
                return ResourceManager.GetString("DeleteAnnot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw an arrow annotation on the chart..
        /// </summary>
        internal static string DrawArrow {
            get {
                return ResourceManager.GetString("DrawArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw an ellipse annotation on the chart..
        /// </summary>
        internal static string DrawEllipse {
            get {
                return ResourceManager.GetString("DrawEllipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a line annotation on the chart..
        /// </summary>
        internal static string DrawLine {
            get {
                return ResourceManager.GetString("DrawLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a polygon annotation on the chart..
        /// </summary>
        internal static string DrawPolygon {
            get {
                return ResourceManager.GetString("DrawPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a multi-jointed line on the chart..
        /// </summary>
        internal static string DrawPolyline {
            get {
                return ResourceManager.GetString("DrawPolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a rectangle annotation on the chart..
        /// </summary>
        internal static string DrawRectangle {
            get {
                return ResourceManager.GetString("DrawRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw a text annotation on the chart..
        /// </summary>
        internal static string DrawText {
            get {
                return ResourceManager.GetString("DrawText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use Ctrl+C to copy the chart to the clipboard!
        ///The icons used in this toolbar are from the Fugue Icon set: http://p.yusukekamiyamane.com/.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the chart..
        /// </summary>
        internal static string PrintChart {
            get {
                return ResourceManager.GetString("PrintChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the chart to an image..
        /// </summary>
        internal static string SaveChart {
            get {
                return ResourceManager.GetString("SaveChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow annotation selection for modifications..
        /// </summary>
        internal static string SelectAnnot {
            get {
                return ResourceManager.GetString("SelectAnnot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set annotation fill transparency (between 0 and 255)..
        /// </summary>
        internal static string SetFillAlpha {
            get {
                return ResourceManager.GetString("SetFillAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set annotation fill colour..
        /// </summary>
        internal static string SetFillColor {
            get {
                return ResourceManager.GetString("SetFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set annotation display layer..
        /// </summary>
        internal static string SetLayer {
            get {
                return ResourceManager.GetString("SetLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set annotation line transparency (between 0 and 255)..
        /// </summary>
        internal static string SetLineAlpha {
            get {
                return ResourceManager.GetString("SetLineAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set annotation line colour..
        /// </summary>
        internal static string SetLineColor {
            get {
                return ResourceManager.GetString("SetLineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Annotation Line Style..
        /// </summary>
        internal static string SetLineStyle {
            get {
                return ResourceManager.GetString("SetLineStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set annotation line thickness..
        /// </summary>
        internal static string SetLineThickness {
            get {
                return ResourceManager.GetString("SetLineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set annotation text..
        /// </summary>
        internal static string SetText {
            get {
                return ResourceManager.GetString("SetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select line or shape display type..
        /// </summary>
        internal static string SetType {
            get {
                return ResourceManager.GetString("SetType", resourceCulture);
            }
        }
    }
}
